// This file was autogenerated by text2c. Do not modify.

#include <string>
#include <vector>

extern std::vector<std::string> base64;
extern std::vector<std::string> dav1d;
extern std::vector<std::string> droidsans;
extern std::vector<std::string> eigen;
extern std::vector<std::string> filesystem;
extern std::vector<std::string> fontstash;
extern std::vector<std::string> gli;
extern std::vector<std::string> libavif;
extern std::vector<std::string> loguru;
extern std::vector<std::string> metalcpp;
extern std::vector<std::string> nlohmannjson;
extern std::vector<std::string> openxrsdk;
extern std::vector<std::string> sdl;
extern std::vector<std::string> sophus;
extern std::vector<std::string> tinygltf;
extern std::vector<std::string> utf8decoder;
extern std::vector<std::string> volk;
extern std::vector<std::string> vulkangltfpbr;
extern std::vector<std::string> vulkanmemoryallocator;
extern std::vector<std::string> wasmfeaturedetect;
extern std::vector<std::string> zstd;
